@ABZProposalWebApi_HostAddress = http://localhost:5273

GET {{ABZProposalWebApi_HostAddress}}/api/Proposal
Accept: application/json



###
POST {{ABZProposalWebApi_HostAddress}}/api/Proposal
Content-Type:application/json
{
  "proposalNo": "PR12345678",
  "regNo": "R123456789",
  "productID": "P123456789",
  "customerID": "C123456789",
  "fromDate": "2024-12-19",
  "toDate": "2024-12-19",
  "idv": 100,
  "agentID": "A123456789",
  "basicAmount": 10,
  "totalAmount": 20
}
