@ABZCustomerWebApi_HostAddress = http://localhost:5151

GET {{ABZCustomerWebApi_HostAddress}}/api/Customer
Accept: application/json

###
POST {{ABZCustomerWebApi_HostAddress}}/api/Customer
Content-Type:application/json
{
  "customerID": "C104",
  "customerName": "Swati",
  "customerPhone": "124567806",
  "customerEmail": "swathi@gmail.com",
  "customerAddress": "Tela"
}
###
GET {{ABZCustomerWebApi_HostAddress}}/api/Customer/C102
Accept: application/json
###
DELETE {{ABZCustomerWebApi_HostAddress}}/api/Customer/C102
Accept: application/json
###
PUT {{ABZCustomerWebApi_HostAddress}}/api/Customer/C103
Content-Type:application/json
{
  "customerID": "C101",
  "customerName": "Hana",
  "customerPhone": "1234567890",
  "customerEmail": "praveen@gmail.com",
  "customerAddress": "Andhra"
}
###